### PR TITLE
Fix rake tasks for Rails 7+

### PR DESCRIPTION
**Pull request by SergeyKolenko**
Use `ActiveRecord::Base.configurations.configs_for` for Rails 7. 
The old method `ActiveRecord::Base.configurations.default_hash` is doesn't work anymore:
Deprecated: https://github.com/rails/rails/blob/6-1-stable/activerecord/CHANGELOG.md#rails-611-january-07-2021
Removed: https://github.com/rails/rails/blob/v7.0.4/activerecord/CHANGELOG.md#rails-700rc1-december-06-2021

### CODE REVIEW

**Comment by PNixx** [comment]
I cannot accept this pull request. We need to support Ruby On Rails 5+.

**Comment by brookemckim** [comment]
@PNixx I would strongly recommend bumping the major version and adding rails 7 support.

**Comment by PNixx** [comment]
I'm planning on updating this summer.

**Comment by PNixx** [comment]
In version `1.0.0` this no longer matters

**Pull request closed without merging**
