### PR TITLE
Add support for HTTP specific settings.

### PR DESCRIPTION
**Pull request by brookemckim**
I have the need to pass in HTTP timeout settings besides the ActiveRecord socket timeouts. This allows you to pass any of the available HTTP settings on every request.

### CODE REVIEW

**Comment by PNixx** [comment]
You can use custom connection:

```ruby
class ActionView < ActiveRecord::Base
  establish_connection(
    adapter: 'clickhouse',
    database: 'database',
    connection: Net::HTTP.start('http://example.org', 8123)
  )
end
```

**Comment by brookemckim** [comment]
@PNixx these options need to be passed a query parameters. How would you make that happen with a custom connection given this? https://github.com/PNixx/clickhouse-activerecord/blob/5e5464a3dd966bf64df803c6d70380dcf7186077/lib/active_record/connection_adapters/clickhouse/schema_statements.rb#L63

**Comment by PNixx** [comment]
You talk about it `"/?#{@config.to_param}"`?

**Comment by brookemckim** [comment]
> You talk about it `"/?#{@config.to_param}"`?

Correct

**Pull request closed without merging**
