### PR TITLE
Added support for Rails 6.1.0;

### PR DESCRIPTION
**Pull request by bdevel**
They must have changed the order things get loaded or the auto load functionality - only require statements needed.

I've only done basic testing but queries worked on Rails 6.1 and 6.0

### CODE REVIEW

**Comment by orlando-labs** [comment]
There are still bugs tho. 
```
[user@serv new-rails-6.1-app]$ rails db:create
Hash
Response code: 400:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 17 (end of query): . Expected one of: IF NOT EXISTS, identifier (version 21.1.2.15 (official build))
Couldn't create 'test_db' database. Please check your configuration.
rails aborted!
```

The reason is a a configuration hash [here](https://github.com/PNixx/clickhouse-activerecord/blob/master/lib/clickhouse-activerecord/tasks.rb#L9) that is a generic not indifferent hash and has only symbolic keys, not the string ones

**Comment by StoneGod** [comment]
Hi, @PNixx, @bdevel. How soon to wait for a fix? Perhaps you need any help with development?

**Comment by PNixx** [comment]
I need test on Rails 5 before merge it.

**Comment by orlando-labs** [comment]
There are breaking changes in Rails 6.1, so I wouldn't expect proper functioning for older rails unless there are some conditional code loads.

**Comment by bdevel** [comment]
@orlando-labs I push a fix for the indifferent hash in the task configuration.

**Comment by orlando-labs** [comment]
Hi, @bdevel , @PNixx, there's still a ruby 3 related keyword arguments passing issue in lib/active_record/connection_adapters/clickhouse/schema_statements.rb
should be something like
```ruby
         def create_table_definition(table_name, options)
           Clickhouse::TableDefinition.new(self, table_name, **options)
         end
 ```

**Comment by bdevel** [comment]
@orlando-labs I pushed that patch you provided. Thanks.

**Comment by orlando-labs** [comment]
Hi, @bdevel, thanks, great. I will try and test your branch today in my app.

**Comment by orlando-labs** [comment]
Hi, @bdevel. Thanks again for the previous commit. It works like a charm. But we've found there's one more [place](https://github.com/bdevel/clickhouse-activerecord/blob/42af034418f337155e6796286af9dec2f3f8dc7e/lib/clickhouse-activerecord/migration.rb#L13) where new keyword argument passing rules strikes back. Should be
```ruby
t.string :version, **version_options
```

**Comment by bdevel** [comment]
@orlando-labs Ok, thanks, I've applied that patch as well with commit 62293fd

**Comment by orlando-labs** [comment]
Hi, @bdevel, @PNixx. Looks like everything's fine after the week of running this code for real tasks

**Comment by MauricioMoraes** [comment]
Thanks for the fix! 
It's working fine for me! Rails 6.1.3 :+1:

**Comment by ferrucc-io** [comment]
Is there any plan of merging this into master? we're using clickhouse without active record and are wondering if it's worth using clickhouse-activerecord on this branch or wait till the fix gets merged

**Comment by bdevel** [comment]
@ferrucc-io I fixed the merge conflict. Report here if any issues.

**Comment by jbwl** [comment]
On a freshly bootstrapped Ruby 2.7.3 / Rails 6.1.3.1 app (API-only mode), I am still getting the error on startup:

`/Users/me/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/bundler/gems/clickhouse-activerecord-a9adf830516b/lib/clickhouse-activerecord/migration.rb:40:in `<module:ClickhouseActiverecord>': **uninitialized constant ActiveRecord::MigrationContext (NameError)**`

I tried with both the current Gem version on Rubygems (4.1.0) as well as the Master branch (4.1.2).

**Comment by bdevel** [comment]
@jbwl The gems that have been released do not support 6.1 yet - this PR has not been merged yet. You're welcome to use my branch in the mean time.

```ruby
# Gemfile

# Use one of these, this one is static to latest commit.
gem 'clickhouse-activerecord',  git: 'https://github.com/bdevel/clickhouse-activerecord.git', :ref => 'f0dbcb0'

# This one will get get any additional updates but potentially new issues
gem 'clickhouse-activerecord', git: 'https://github.com/bdevel/clickhouse-activerecord.git', branch: 'rails-6.1-support'
```

**Comment by mattiagiuffrida-st** [comment]
@PNixx please please we need this one merged 🙏

**Comment by mattiagiuffrida-st** [comment]
@bdevel I'm still experiencing [this issue](https://github.com/PNixx/clickhouse-activerecord/issues/38) when using your PR with Ruby 3.0.1, though I thought [you fixed it](https://github.com/PNixx/clickhouse-activerecord/commit/62293fdf7cfda46611276932041459ba20bc9f37) already?

**Comment by iMacTia** [comment]
@bdevel I'm still experiencing [this issue](https://github.com/PNixx/clickhouse-activerecord/issues/38) when using your PR with Ruby 3.0.1, though I thought [you fixed it](https://github.com/PNixx/clickhouse-activerecord/commit/62293fdf7cfda46611276932041459ba20bc9f37) already?

@PNixx please please we need this one merged and released 🙏

**Comment by iMacTia** [comment]
Thanks a lot @PNixx 🎉 !

**Comment by ukolovda** [comment]
Hi!
@PNixx , rubygems.org still doesn't have version 0.5.0
https://rubygems.org/gems/clickhouse-activerecord/versions

Please, publish 0.5.0 version.
Thank you!

**Comment by PNixx** [comment]
For some reason I have not published in rubygems. 0.5.0 published now.

**Comment by ukolovda** [comment]
> For some reason I have not published in rubygems. 0.5.0 published now.

Thank you!

**Pull request merged**
