### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by Bugagazavr**
What changed:

- initial migrations support ( create table, drop table, add column, remove column, raw sql execute )
- query execution moved to statements module
- replace rails dependency, by active record dependency
- added some specs

### CODE REVIEW

**Comment by Bugagazavr** [comment]
it would be nice to see travis or something else in this project

**Comment by PNixx** [comment]
Good work, thanks! But, I think we not need show technical information in to log (DESCRIBE TABLE, SHOW TABLES and etc.). For these purposes, I make a 2 methods:
```
# Request without log (for table list, table structure)
def query(sql, _name = nil)	
  res = @connection.post("/?#{@config.to_param}", "#{sql} FORMAT JSONCompact")	
  raise ActiveRecord::ActiveRecordError, "Response code: #{res.code}:\n#{res.body}" unless res.code.to_i == 200	
  JSON.parse res.body	
end	

# Request with log
def execute(sql, name = nil)	
  log(sql, "#{adapter_name} #{name}") do	
    query sql, name	
  end	
end
```

Please, fix it.

**Comment by PNixx** [comment]
I not see technical information by first request on rails console.
```
2.3.1 :003 > Order.first
[master]  Order Load (5.8ms)  SELECT  "orders".* FROM "orders" ORDER BY "orders"."id" ASC LIMIT 1
```
I think, you can use options from `database.yml`. @Bugagazavr what do you think?

**Comment by Bugagazavr** [comment]
@PNixx ok, i'l add option to connection configuration.

You also should know currently supported only `up` and `change` migrations, `down` is going fail, because need to know how to map `DELETE FROM schema_migrations WHERE version = ?` to `ALTER TABLE schema_migrations DELETE WHERE version = some version`

**Comment by PNixx** [comment]
The first thing that comes to mind is to create a new table, copy data, rename old table, rename new table to schema_migrations, drop old table. :) But, I think it is bad.

**Comment by Bugagazavr** [comment]
Ok, now two methods:

-  `do_execute` with generic logging logic and format param ( by default `JSONCompact` ) this can helps in future, for `multi_insert` feature when we can pass `CSV`, `JSONEachRow` data
- `do_system_execute` with format `JSONCompact`, and logging only if debug property is set

**Pull request merged**
